version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rpENafFkaevsnJWE3ihLuORe3n
      MYSQL_DATABASE: dbcmc7ibbbe00029ykc14ve0v1s
      MYSQL_USER: ucmc7ibbbc00009ykc2yak0dd0
      MYSQL_PASSWORD: p1CZL6wf9dpEpT1CglQMwbVJq
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ucmc7bbc00009ykc2yak0dd0
      WORDPRESS_DB_PASSWORD: p1CZL6wf9dpEpT1CglQMwbVJq
      WORDPRESS_DB_NAME: dbcmc7ibbbe00029ykc14ve0v1s
    volumes:
      - wordpress_data:/var/www/html

volumes:
  db_data:
  wordpress_data:
