version: "3.8"

services:
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: cmc7ibbbf0000kc9yf1f2buag:3306  # Your external DB host and port
      WORDPRESS_DB_USER: cmc7ibbbd00019ykc5rdv2ggh       # Root user
      WORDPRESS_DB_PASSWORD: rpENafFkaevsnJWE3ihLuORe3n  # Root password
      WORDPRESS_DB_NAME: cmc7ibbbe00029ykc14ve0v1s       # Your DB name
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:
