version: "3.8"

services:
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: cmc7ibbbf0000kc9yf1f2buag:9000  # Your external DB host and port
      WORDPRESS_DB_USER: ucmc7ibbbc00009ykc2yak0dd0       # Root user
      WORDPRESS_DB_PASSWORD: p1CZL6wf9dpEpT1CglQMwbVJq  # Root password
      WORDPRESS_DB_NAME: dbcmc7ibbbe00029ykc14ve0v1s       # Your DB name
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:
